apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend-service-account.yaml
  - backend-role.yaml
  - backend-rolebinding.yaml
  - backend-service.yaml
  - backend-deployment.yaml
  - frontend-service.yaml
  - frontend-deployment.yaml
  - database-service.yaml
  - database-statefulset.yaml
  - redis-service.yaml
  - redis-deployment.yaml
  - redis-pvc.yaml
  - ingress.yaml
  - app-configmap.yaml
  - app-secrets.yaml
  - monitoring/prometheus/prometheus.yaml
  - monitoring/alertmanager/alertmanager.yaml
  - monitoring/loki/loki-grafana.yaml

namespace: default

commonLabels:
  app.kubernetes.io/name: blockguardian
  app.kubernetes.io/managed-by: kustomize

generatorOptions:
  disableNameSuffixHash: true
